name: Juice Shop with Dependency Check

on:
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: self-hosted

    env: 
      DPC_PATH: ${{ vars.DPC_PATH }}
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '26.x'

      - name: Verify tools
        run: |
            node -v 
            npm -v 
            git --version

      - name: Clone Juice Shop
        run: git clone https://github.com/juice-shop/juice-shop.git


      - name: Installing Dependencies
        run: |
          cd juice-shop/
          npm install > ../juice_install.log 2>&1 


      - name: Start Juice Shop
        run: |
            cd juice-shop/
            nohup npm start > ../juice_start.log 2>&1 &
            sleep 20
            echo "Juice Shop is started"

      - name: Dependency Check 
        run: | 
            $DPC_PATH/dependency-check.sh --scan juice-shop/ --exclude "juice-shop/test/** --disableAssembly --disableYarnAudi --format HTML --out reports/ --nvdApiKey "$NVD_API_KEY" 

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/



